import { Inter } from 'next/font/google'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <QueryClientProvider client={new QueryClient()}>
        <body className={inter.className}>{children}</body>
      </QueryClientProvider>
    </html>
  )
}
